version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=citaeasydb
      - MYSQL_USER=citaeasy
      - MYSQL_PASSWORD=cita_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - citaeasy_network

  api:
    image: derianaguilarfsc/citaeasy_api:latest
    container_name: citaeasy
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://citaeasy:cita_pass@db/citaeasydb
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - citaeasy_network

volumes:
  db_data:

networks:
  citaeasy_network: